CREATE USER APP_USER IDENTIFIED BY "P@ssw0rd";

GRANT CONNECT, RESOURCE, CREATE VIEW TO APP_USER;
ALTER USER APP_USER QUOTA UNLIMITED ON USERS;

ALTER SESSION SET CURRENT_SCHEMA = APP_USER;

CREATE SEQUENCE SEQ_ASPNET_USERS
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

CREATE SEQUENCE SEQ_ASPNET_ROLES
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

CREATE SEQUENCE SEQ_USER_CLAIMS
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

CREATE SEQUENCE SEQ_ROLE_CLAIMS
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

CREATE TABLE ASPNET_USERS
(
	Id                      NUMBER(19, 0)           NOT NULL,
	UserName                VARCHAR2(256 CHAR)      NOT NULL,
	NormalizedUserName      VARCHAR2(256 CHAR)      NOT NULL,
	Email                   VARCHAR2(256 CHAR)      NULL,
	NormalizedEmail         VARCHAR2(256 CHAR)      NULL,
	EmailConfirmed          NUMBER(1, 0)            DEFAULT 0 NOT NULL,
	PasswordHash            VARCHAR2(2000 CHAR)     NULL,
	SecurityStamp           VARCHAR2(36 CHAR)       NULL,
	ConcurrencyStamp        VARCHAR2(36 CHAR)       NOT NULL,
	PhoneNumber             VARCHAR2(64 CHAR)       NULL,
	PhoneNumberConfirmed    NUMBER(1, 0)            DEFAULT 0 NOT NULL,
	TwoFactorEnabled        NUMBER(1, 0)            DEFAULT 0 NOT NULL,
	LockoutEnd              TIMESTAMP WITH TIME ZONE NULL,
	LockoutEnabled          NUMBER(1, 0)            DEFAULT 0 NOT NULL,
	AccessFailedCount       NUMBER(10, 0)           DEFAULT 0 NOT NULL,
	FirstName               NVARCHAR2(256)          NULL,
	LastName                NVARCHAR2(256)          NULL,
	IsActive                NUMBER(1, 0)            DEFAULT 1 NOT NULL,
	CreatedAtUtc            TIMESTAMP               NOT NULL,
	LastLoggedInAtUtc       TIMESTAMP               NULL,
	PasswordChangedAtUtc    TIMESTAMP               NULL,

	CONSTRAINT PK_ASPNET_USERS PRIMARY KEY (Id),
	CONSTRAINT UQ_USERS_NORMALIZED_NAME UNIQUE (NormalizedUserName),
	CONSTRAINT CK_USERS_EMAIL_CONF CHECK (EmailConfirmed IN (0, 1)),
	CONSTRAINT CK_USERS_PHONE_CONF CHECK (PhoneNumberConfirmed IN (0, 1)),
	CONSTRAINT CK_USERS_TWO_FACTOR CHECK (TwoFactorEnabled IN (0, 1)),
	CONSTRAINT CK_USERS_LOCKOUT CHECK (LockoutEnabled IN (0, 1)),
	CONSTRAINT CK_USERS_IS_ACTIVE CHECK (IsActive IN (0, 1)),
	CONSTRAINT CK_USERS_FAILED_COUNT CHECK (AccessFailedCount >= 0)
);

CREATE TABLE ASPNET_ROLES
(
	Id                  NUMBER(19, 0)       NOT NULL,
	Name                VARCHAR2(256 CHAR)  NOT NULL,
	NormalizedName      VARCHAR2(256 CHAR)  NOT NULL,
	ConcurrencyStamp    VARCHAR2(36 CHAR)   NOT NULL,

	CONSTRAINT PK_ASPNET_ROLES PRIMARY KEY (Id),
	CONSTRAINT UQ_ROLES_NORMALIZED_NAME UNIQUE (NormalizedName)
);

CREATE TABLE ASPNET_USER_CLAIMS
(
	Id          NUMBER(19, 0)       NOT NULL,
	UserId      NUMBER(19, 0)       NOT NULL,
	ClaimType   VARCHAR2(256 BYTE)   NOT NULL,
	ClaimValue  VARCHAR2(1000 BYTE)  NOT NULL,

	CONSTRAINT PK_ASPNET_USER_CLAIMS PRIMARY KEY (Id),
	CONSTRAINT UQ_USER_CLAIM UNIQUE (UserId, ClaimType, ClaimValue),
	CONSTRAINT FK_USER_CLAIM_USER FOREIGN KEY (UserId)
		REFERENCES ASPNET_USERS (Id) ON DELETE CASCADE
);

CREATE TABLE ASPNET_USER_ROLE_CLAIMS
(
	Id          NUMBER(19, 0)       NOT NULL,
	RoleId      NUMBER(19, 0)       NOT NULL,
	ClaimType   VARCHAR2(256 BYTE)   NOT NULL,
	ClaimValue  VARCHAR2(1000 BYTE)  NOT NULL,

	CONSTRAINT PK_ASPNET_ROLE_CLAIMS PRIMARY KEY (Id),
	CONSTRAINT UQ_ROLE_CLAIM UNIQUE (RoleId, ClaimType, ClaimValue),
	CONSTRAINT FK_ROLE_CLAIM_ROLE FOREIGN KEY (RoleId)
		REFERENCES ASPNET_ROLES (Id) ON DELETE CASCADE
);

CREATE TABLE ASPNET_USER_ROLES
(
	UserId  NUMBER(19, 0) NOT NULL,
	RoleId  NUMBER(19, 0) NOT NULL,

	CONSTRAINT PK_ASPNET_USER_ROLES PRIMARY KEY (UserId, RoleId),
	CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (UserId)
		REFERENCES ASPNET_USERS (Id) ON DELETE CASCADE,
	CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (RoleId)
		REFERENCES ASPNET_ROLES (Id) ON DELETE CASCADE
);

CREATE TABLE ASPNET_USER_LOGINS
(
	UserId                  NUMBER(19, 0)       NOT NULL,
	LoginProvider           VARCHAR2(128 BYTE)  NOT NULL,
	ProviderKey             VARCHAR2(256 BYTE)  NOT NULL,
	ProviderDisplayName     VARCHAR2(256 CHAR)  NULL,

	CONSTRAINT PK_ASPNET_USER_LOGINS PRIMARY KEY (LoginProvider, ProviderKey),
	CONSTRAINT FK_USER_LOGIN_USER FOREIGN KEY (UserId)
		REFERENCES ASPNET_USERS (Id) ON DELETE CASCADE
);

CREATE TABLE ASPNET_USER_TOKENS
(
	UserId          NUMBER(19, 0)       NOT NULL,
	LoginProvider   VARCHAR2(128 BYTE)  NOT NULL,
	Name            VARCHAR2(128 BYTE)  NOT NULL,
	Value           VARCHAR2(4000 BYTE) NULL,

	CONSTRAINT PK_ASPNET_USER_TOKENS PRIMARY KEY (UserId, LoginProvider, Name),
	CONSTRAINT FK_USER_TOKEN_USER FOREIGN KEY (UserId)
		REFERENCES ASPNET_USERS (Id) ON DELETE CASCADE
);

CREATE INDEX IX_USERS_NORMALIZED_EMAIL
	ON ASPNET_USERS (NormalizedEmail);

CREATE INDEX IX_USERS_FIRST_NAME
	ON ASPNET_USERS (FirstName);

CREATE INDEX IX_USERS_LAST_NAME
	ON ASPNET_USERS (LastName);

CREATE INDEX IX_USERS_UPPER_NAMES
	ON ASPNET_USERS (UPPER(FirstName), UPPER(LastName));

CREATE INDEX IX_USER_CLAIMS_USER_ID
	ON ASPNET_USER_CLAIMS (UserId);

CREATE INDEX IX_ROLE_CLAIMS_ROLE_ID
	ON ASPNET_USER_ROLE_CLAIMS (RoleId);

CREATE INDEX IX_USER_ROLES_USER_ID
	ON ASPNET_USER_ROLES (UserId);

CREATE INDEX IX_USER_ROLES_ROLE_ID
	ON ASPNET_USER_ROLES (RoleId);

CREATE INDEX IX_USER_LOGINS_USER_ID
	ON ASPNET_USER_LOGINS (UserId);

CREATE INDEX IX_USER_TOKENS_USER_ID
	ON ASPNET_USER_TOKENS (UserId);

CREATE INDEX IX_USER_CLAIMS_LOOKUP
	ON ASPNET_USER_CLAIMS (ClaimType, ClaimValue, UserId);


